# Generated by Django 6.0 on 2026-01-05 09:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Variant ',
                'verbose_name_plural': 'Variant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='brands', to='product.category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specifications', tinymce.models.HTMLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('free_shipping', 'Free Shipping'), ('free_gift', 'Free Gift')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Promotion',
                'verbose_name_plural': 'Product Promotions',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variant',
                'ordering': ['product', '-is_default', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('text', 'Text'), ('color', 'Color'), ('image', 'Image')], default='text', max_length=10)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Enter color code in hex format (e.g., #FF0000)', max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.variantattribute')),
            ],
            options={
                'verbose_name': ' Attribute',
                'verbose_name_plural': ' Attribute',
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_attributes',
            field=models.ManyToManyField(related_name='product_variants', to='product.variantattributevalue'),
        ),
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_main', to='product.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_related', to='product.product')),
            ],
            options={
                'verbose_name': 'Frequently Bought Together',
                'verbose_name_plural': 'Frequently Bought Together',
                'ordering': ['display_order'],
                'unique_together': {('main_product', 'related_product')},
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deal_type', models.CharField(choices=[('deal_of_day', 'Deal of the Day'), ('flash_sale', 'Flash Sale'), ('clearance', 'Clearance'), ('seasonal', 'Seasonal Sale'), ('bundle', 'Bundle Deal'), ('limited_time', 'Limited Time Offer')], max_length=50)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_quantity', models.PositiveIntegerField(help_text='Total units allocated for this deal', validators=[django.core.validators.MinValueValidator(1)])),
                ('sold_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_quantity_per_order', models.PositiveIntegerField(default=5, help_text='Maximum quantity per order')),
                ('free_shipping', models.BooleanField(default=False)),
                ('shipping_message', models.CharField(blank=True, max_length=100)),
                ('free_gift', models.BooleanField(default=False)),
                ('gift_message', models.CharField(blank=True, max_length=100)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#FF0000', max_length=7)),
                ('highlight_features', models.JSONField(blank=True, default=list, help_text="Featured specs to display. E.g., [{'label': 'Display', 'value': '6.67 inches'}]")),
                ('description', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Leave blank if deal applies to all variants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deal',
                'db_table': 'deals',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['deal_type', 'is_active'], name='deals_deal_ty_2b27c8_idx'), models.Index(fields=['start_date', 'end_date'], name='deals_start_d_f44f07_idx'), models.Index(fields=['is_featured', 'is_active'], name='deals_is_feat_b15b71_idx'), models.Index(fields=['product', 'variant'], name='deals_product_a1e62b_idx'), models.Index(fields=['slug'], name='deals_slug_00d031_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Viewed Product',
                'verbose_name_plural': 'Recently Viewed Product',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.productvariant')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variantattributevalue')),
            ],
            options={
                'verbose_name': 'Variant Attribute Mapping',
                'verbose_name_plural': 'Variant Attribute Mapping',
                'unique_together': {('variant', 'attribute_value')},
            },
        ),
    ]
