# Generated by Django 6.0 on 2025-12-18 05:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
