# Generated by Django 6.0 on 2026-01-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantAttributeValue',
        ),
    ]
