# Generated by Django 6.0 on 2026-01-28 15:32

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_productvariantattributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('combo_regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combo_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Combo',
                'verbose_name_plural': 'Product Combos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productcombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('combo', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='FrequentlyBoughtTogether',
        ),
    ]
