# Generated by Django 6.0 on 2025-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productpromotion_frequentlyboughttogether_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='promotion_type',
            field=models.CharField(choices=[('free_shipping', 'Free Shipping'), ('free_gift', 'Free Gift')], max_length=20),
        ),
    ]
