# Generated by Django 6.0 on 2026-01-28 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcombo_productcomboitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombo',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='product.product'),
        ),
    ]
