# Generated by Django 6.0 on 2026-01-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_add_main_product_to_productcombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombo',
            name='main_product',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='product.product'),
            preserve_default=False,
        ),
    ]
