# Generated by Django 6.0 on 2025-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
