# Generated by Django 6.0 on 2026-01-28 16:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productcombo_main_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping', models.BooleanField(default=False)),
                ('free_gift_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Deal Extra',
                'verbose_name_plural': 'Deal Extras',
            },
        ),
        migrations.CreateModel(
            name='DealStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Deal Stat',
                'verbose_name_plural': 'Deal Stats',
            },
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_deal_ty_2b27c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_start_d_f44f07_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_is_feat_b15b71_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_product_a1e62b_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='deals_slug_00d031_idx',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_percent',
            field=models.PositiveIntegerField(default=11, help_text='Percentage discount', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('flash', 'Flash Sale'), ('daily', 'Deal of the Day'), ('seasonal', 'Seasonal Sale'), ('clearance', 'Clearance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.productvariant'),
        ),
        migrations.AlterModelTable(
            name='deal',
            table=None,
        ),
        migrations.AddField(
            model_name='dealextra',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.deal'),
        ),
        migrations.AddField(
            model_name='dealstat',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.deal'),
        ),
        migrations.RemoveField(
            model_name='deal',
            name='badge_color',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='free_gift',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='free_shipping',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='gift_message',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='highlight_features',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='max_quantity_per_order',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='shipping_message',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='sold_quantity',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='view_count',
        ),
    ]
