# Generated by Django 6.0 on 2025-12-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='logo',
            new_name='image',
        ),
    ]
