# Generated by Django 6.0 on 2026-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_simplify_deal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity sold so far'),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity available for this deal'),
        ),
    ]
