# Generated by Django 6.0 on 2026-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_add_deal_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='variant',
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('flash', 'Flash Sale'), ('daily', 'Deal of the Day'), ('seasonal', 'Seasonal Sale')], max_length=20),
        ),
    ]
