# Generated by Django 6.0 on 2025-12-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_logo_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('promotion_description', models.TextField(blank=True, default='Hurry up! Promotion will expire soon.', help_text='Description for the promotion', null=True)),
                ('promotion_start', models.DateTimeField()),
                ('promotion_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.product')),
            ],
            options={
                'verbose_name': 'Deal of the Day',
                'verbose_name_plural': 'Deals of the Day',
                'ordering': ['-promotion_start'],
            },
        ),
    ]
