# Generated by Django 6.0 on 2025-12-22 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_dealoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deal_type', models.CharField(choices=[('deal_of_day', 'Deal of the Day'), ('flash_sale', 'Flash Sale'), ('clearance', 'Clearance'), ('seasonal', 'Seasonal Sale'), ('bundle', 'Bundle Deal'), ('limited_time', 'Limited Time Offer')], max_length=50)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_quantity', models.PositiveIntegerField(help_text='Total units allocated for this deal', validators=[django.core.validators.MinValueValidator(1)])),
                ('sold_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_quantity_per_order', models.PositiveIntegerField(default=5, help_text='Maximum quantity per order')),
                ('free_shipping', models.BooleanField(default=False)),
                ('shipping_message', models.CharField(blank=True, max_length=100)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#FF0000', max_length=7)),
                ('highlight_features', models.JSONField(blank=True, default=list, help_text="Featured specs to display. E.g., [{'label': 'Display', 'value': '6.67 inches'}]")),
                ('description', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Leave blank if deal applies to all variants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.productvariant')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DealOfTheDay',
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_type', 'is_active'], name='deals_deal_ty_2b27c8_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date', 'end_date'], name='deals_start_d_f44f07_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_featured', 'is_active'], name='deals_is_feat_b15b71_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['product', 'variant'], name='deals_product_a1e62b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['slug'], name='deals_slug_00d031_idx'),
        ),
    ]
