# Generated by Django 6.0 on 2026-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_deal_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealstat',
            name='deal',
        ),
        migrations.AddField(
            model_name='deal',
            name='free_gift_text',
            field=models.CharField(blank=True, help_text='Free gift description', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='Free shipping for this deal'),
        ),
        migrations.AddField(
            model_name='deal',
            name='purchases',
            field=models.PositiveIntegerField(default=0, help_text='Number of purchases made'),
        ),
        migrations.AddField(
            model_name='deal',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views for this deal'),
        ),
        migrations.DeleteModel(
            name='DealExtra',
        ),
        migrations.DeleteModel(
            name='DealStat',
        ),
    ]
