# Generated by Django 6.0 on 2026-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_dealstat_deal_deal_free_gift_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('free_shipping', 'Free Shipping'), ('free_gift', 'Free Gift')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='product.product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='product_pro_is_acti_95e7ea_idx'),
        ),
    ]
