# Generated by Django 6.0 on 2025-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_deal_delete_dealoftheday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='free_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='gift_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
