# Generated by Django 6.0 on 2026-02-24 07:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_promotion_delete_productpromotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
