# Generated by Django 6.0 on 2025-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_deal_free_gift_deal_gift_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyboughttogether',
            options={'ordering': ['display_order'], 'verbose_name': 'Frequently Bought Together', 'verbose_name_plural': 'Frequently Bought Together'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcomparison',
            options={'ordering': ['added_at'], 'verbose_name': 'Product Comparison', 'verbose_name_plural': 'Product Comparisons'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productpromotion',
            options={'verbose_name': 'Product Promotion', 'verbose_name_plural': 'Product Promotions'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', '-is_default', 'price'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='productvariantattributevalue',
            options={'verbose_name': 'Variant Attribute Mapping', 'verbose_name_plural': 'Variant Attribute Mappings'},
        ),
        migrations.AlterModelOptions(
            name='variantattribute',
            options={'ordering': ['name'], 'verbose_name': 'Variant Attribute', 'verbose_name_plural': 'Variant Attributes'},
        ),
        migrations.AlterModelOptions(
            name='variantattributevalue',
            options={'ordering': ['attribute', 'value'], 'verbose_name': 'Variant Attribute Value', 'verbose_name_plural': 'Variant Attribute Values'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
