# Generated by Django 6.0 on 2026-02-24 08:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_promotion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Only fill for free_gift promotion type', null=True),
        ),
    ]
