# Generated by Django 6.0 on 2025-12-27 15:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_recentlyviewedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
