# Generated by Django 6.0 on 2026-02-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_promotion_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-is_featured', 'display_order', '-created_at'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deal'},
        ),
        migrations.AlterModelOptions(
            name='productcombo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Combo', 'verbose_name_plural': 'Product Combo'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotion'},
        ),
    ]
