# Generated by Django 6.0 on 2026-02-25 10:27

import filehub.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_deal_options_alter_productcombo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, null=True, upload_to=None),
        ),
    ]
