# Generated by Django 6.0 on 2026-02-25 10:32

import filehub.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=filehub.fields.ImagePickerField(blank=True, file_ext=None, file_type=None, null=True, upload_to='categories/'),
        ),
    ]
