# Generated by Django 6.0 on 2025-12-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_brand_options_alter_category_options_and_more'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Small description under title', max_length=255)),
                ('image', models.ImageField(help_text='Main card image', upload_to='curated/')),
                ('badge_text', models.CharField(blank=True, help_text='Example: SALE, 50% OFF', max_length=50)),
                ('badge_color', models.CharField(default='green', help_text='CSS color or Tailwind class', max_length=20)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('link_url', models.URLField(help_text='Where the card redirects')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order (lower comes first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'verbose_name': 'Curated Item',
                'verbose_name_plural': 'Curated Items',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
