# Generated by Django 6.0 on 2026-02-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings_shipping_cost_sitesettings_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
