# Generated by Django 6.0 on 2025-12-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_curateditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curateditem',
            name='badge_color',
        ),
        migrations.RemoveField(
            model_name='curateditem',
            name='badge_text',
        ),
    ]
