# Generated by Django 6.0 on 2025-12-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_curateditem_badge_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curateditem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Frontend route (e.g. /products/ipad-mini-6/)', max_length=255),
        ),
    ]
