# Generated by Django 6.0 on 2025-12-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_curateditem_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('photo', 'Photo Ad'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('inline', 'Inline Content'), ('video', 'Video Ad')], default='banner', max_length=20),
        ),
    ]
