# Generated by Django 6.0 on 2025-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0014_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_brands',
            field=models.ManyToManyField(blank=True, null=True, to='product.brand'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, null=True, to='product.category'),
        ),
    ]
