# Generated by Django 6.0 on 2026-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_brands',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='product.brand'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='product.category'),
        ),
    ]
