# Generated by Django 6.0 on 2026-01-28 05:20

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Main page content (HTML allowed)', null=True)),
                ('excerpt', tinymce.models.HTMLField(blank=True, help_text='Short summary of the page', max_length=300, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('seo_title', models.CharField(blank=True, help_text='Custom title for search engines', max_length=70)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select a page OR enter a custom URL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.page'),
        ),
    ]
