# Generated by Django 6.0 on 2026-01-28 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_sku_orderitem_product_and_more'),
        ('product', '0011_remove_deal_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.deal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage applied from deal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price before discount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
