# Generated by Django 6.0 on 2026-01-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_deal_tracking'),
        ('product', '0011_remove_deal_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.productcombo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_combo_parent',
            field=models.BooleanField(default=False, help_text='True if this is the combo bundle itself'),
        ),
    ]
