# Generated by Django 6.0 on 2026-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_combo_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('khalti', 'Khalti'), ('esewa', 'eSewa'), ('bank_transfer', 'Bank Transfer')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=200, null=True),
        ),
    ]
