# Generated by Django 6.0 on 2026-02-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_method_order_payment_transaction_id'),
        ('product', '0015_alter_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_shipping_applied',
            field=models.BooleanField(default=False, help_text='Whether free shipping promotion was applied'),
        ),
        migrations.AddField(
            model_name='order',
            name='free_shipping_promotion',
            field=models.ForeignKey(blank=True, limit_choices_to={'promotion_type': 'free_shipping'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_with_free_shipping', to='product.promotion'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='free_gift_detail',
            field=models.CharField(blank=True, help_text='Details of free gift if promotion applied', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.promotion'),
        ),
    ]
