# Generated by Django 6.0 on 2026-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_free_shipping_applied_and_more'),
        ('product', '0015_alter_promotion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='free_shipping_applied',
        ),
        migrations.RemoveField(
            model_name='order',
            name='free_shipping_promotion',
        ),
        migrations.AddField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, help_text='Promotions applied to this order', related_name='orders', to='product.promotion'),
        ),
    ]
