# Generated by Django 6.0 on 2026-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_free_shipping_applied_and_more'),
        ('product', '0015_alter_promotion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='promotion',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotions',
            field=models.ManyToManyField(blank=True, help_text='Promotions applied to this order item', related_name='order_items', to='product.promotion'),
        ),
    ]
